services:
  iot-platform-go:
    build:
      context: ../..
      dockerfile: deployments/app/Dockerfile
    container_name: iot-platform-go
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/api/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - CONFIG_PATH=configs/config.prod.yaml
    networks:
      - 1panel-network
    volumes:
      - ../../configs:/app/configs:ro
      - ../../build/iot-platform:/app/iot-platform:ro
    restart: unless-stopped

networks:
  1panel-network:
    external: true
