// Code generated by ent, DO NOT EDIT.

package mqttpublishlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mqttpublishlog type in the database.
	Label = "mqtt_publish_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldQos holds the string denoting the qos field in the database.
	FieldQos = "qos"
	// FieldRetained holds the string denoting the retained field in the database.
	FieldRetained = "retained"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldBrokerURL holds the string denoting the broker_url field in the database.
	FieldBrokerURL = "broker_url"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the mqttpublishlog in the database.
	Table = "mqtt_publish_logs"
)

// Columns holds all SQL columns for mqttpublishlog fields.
var Columns = []string{
	FieldID,
	FieldTopic,
	FieldPayload,
	FieldQos,
	FieldRetained,
	FieldClientID,
	FieldBrokerURL,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	TopicValidator func(string) error
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload string
	// DefaultQos holds the default value on creation for the "qos" field.
	DefaultQos int
	// DefaultRetained holds the default value on creation for the "retained" field.
	DefaultRetained bool
	// DefaultClientID holds the default value on creation for the "client_id" field.
	DefaultClientID string
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// DefaultBrokerURL holds the default value on creation for the "broker_url" field.
	DefaultBrokerURL string
	// BrokerURLValidator is a validator for the "broker_url" field. It is called by the builders before save.
	BrokerURLValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)

// OrderOption defines the ordering options for the MqttPublishLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTopic orders the results by the topic field.
func ByTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopic, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByQos orders the results by the qos field.
func ByQos(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQos, opts...).ToFunc()
}

// ByRetained orders the results by the retained field.
func ByRetained(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetained, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByBrokerURL orders the results by the broker_url field.
func ByBrokerURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrokerURL, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}
