// Code generated by ent, DO NOT EDIT.

package mqttpublishlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/yu/iot-platform-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldID, id))
}

// Topic applies equality check predicate on the "topic" field. It's identical to TopicEQ.
func Topic(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldTopic, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldPayload, v))
}

// Qos applies equality check predicate on the "qos" field. It's identical to QosEQ.
func Qos(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldQos, v))
}

// Retained applies equality check predicate on the "retained" field. It's identical to RetainedEQ.
func Retained(v bool) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldRetained, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldClientID, v))
}

// BrokerURL applies equality check predicate on the "broker_url" field. It's identical to BrokerURLEQ.
func BrokerURL(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldBrokerURL, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldCreateTime, v))
}

// TopicEQ applies the EQ predicate on the "topic" field.
func TopicEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldTopic, v))
}

// TopicNEQ applies the NEQ predicate on the "topic" field.
func TopicNEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldTopic, v))
}

// TopicIn applies the In predicate on the "topic" field.
func TopicIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldTopic, vs...))
}

// TopicNotIn applies the NotIn predicate on the "topic" field.
func TopicNotIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldTopic, vs...))
}

// TopicGT applies the GT predicate on the "topic" field.
func TopicGT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldTopic, v))
}

// TopicGTE applies the GTE predicate on the "topic" field.
func TopicGTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldTopic, v))
}

// TopicLT applies the LT predicate on the "topic" field.
func TopicLT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldTopic, v))
}

// TopicLTE applies the LTE predicate on the "topic" field.
func TopicLTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldTopic, v))
}

// TopicContains applies the Contains predicate on the "topic" field.
func TopicContains(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContains(FieldTopic, v))
}

// TopicHasPrefix applies the HasPrefix predicate on the "topic" field.
func TopicHasPrefix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasPrefix(FieldTopic, v))
}

// TopicHasSuffix applies the HasSuffix predicate on the "topic" field.
func TopicHasSuffix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasSuffix(FieldTopic, v))
}

// TopicEqualFold applies the EqualFold predicate on the "topic" field.
func TopicEqualFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEqualFold(FieldTopic, v))
}

// TopicContainsFold applies the ContainsFold predicate on the "topic" field.
func TopicContainsFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContainsFold(FieldTopic, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContainsFold(FieldPayload, v))
}

// QosEQ applies the EQ predicate on the "qos" field.
func QosEQ(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldQos, v))
}

// QosNEQ applies the NEQ predicate on the "qos" field.
func QosNEQ(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldQos, v))
}

// QosIn applies the In predicate on the "qos" field.
func QosIn(vs ...int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldQos, vs...))
}

// QosNotIn applies the NotIn predicate on the "qos" field.
func QosNotIn(vs ...int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldQos, vs...))
}

// QosGT applies the GT predicate on the "qos" field.
func QosGT(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldQos, v))
}

// QosGTE applies the GTE predicate on the "qos" field.
func QosGTE(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldQos, v))
}

// QosLT applies the LT predicate on the "qos" field.
func QosLT(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldQos, v))
}

// QosLTE applies the LTE predicate on the "qos" field.
func QosLTE(v int) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldQos, v))
}

// RetainedEQ applies the EQ predicate on the "retained" field.
func RetainedEQ(v bool) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldRetained, v))
}

// RetainedNEQ applies the NEQ predicate on the "retained" field.
func RetainedNEQ(v bool) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldRetained, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContainsFold(FieldClientID, v))
}

// BrokerURLEQ applies the EQ predicate on the "broker_url" field.
func BrokerURLEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldBrokerURL, v))
}

// BrokerURLNEQ applies the NEQ predicate on the "broker_url" field.
func BrokerURLNEQ(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldBrokerURL, v))
}

// BrokerURLIn applies the In predicate on the "broker_url" field.
func BrokerURLIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldBrokerURL, vs...))
}

// BrokerURLNotIn applies the NotIn predicate on the "broker_url" field.
func BrokerURLNotIn(vs ...string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldBrokerURL, vs...))
}

// BrokerURLGT applies the GT predicate on the "broker_url" field.
func BrokerURLGT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldBrokerURL, v))
}

// BrokerURLGTE applies the GTE predicate on the "broker_url" field.
func BrokerURLGTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldBrokerURL, v))
}

// BrokerURLLT applies the LT predicate on the "broker_url" field.
func BrokerURLLT(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldBrokerURL, v))
}

// BrokerURLLTE applies the LTE predicate on the "broker_url" field.
func BrokerURLLTE(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldBrokerURL, v))
}

// BrokerURLContains applies the Contains predicate on the "broker_url" field.
func BrokerURLContains(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContains(FieldBrokerURL, v))
}

// BrokerURLHasPrefix applies the HasPrefix predicate on the "broker_url" field.
func BrokerURLHasPrefix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasPrefix(FieldBrokerURL, v))
}

// BrokerURLHasSuffix applies the HasSuffix predicate on the "broker_url" field.
func BrokerURLHasSuffix(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldHasSuffix(FieldBrokerURL, v))
}

// BrokerURLEqualFold applies the EqualFold predicate on the "broker_url" field.
func BrokerURLEqualFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEqualFold(FieldBrokerURL, v))
}

// BrokerURLContainsFold applies the ContainsFold predicate on the "broker_url" field.
func BrokerURLContainsFold(v string) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldContainsFold(FieldBrokerURL, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.FieldLTE(FieldCreateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MqttPublishLog) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MqttPublishLog) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MqttPublishLog) predicate.MqttPublishLog {
	return predicate.MqttPublishLog(sql.NotPredicates(p))
}
