// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/redis/go-redis/v9"
	"github.com/yu/iot-platform-go/cache"
	"github.com/yu/iot-platform-go/config"
	"github.com/yu/iot-platform-go/repository"
	"github.com/yu/iot-platform-go/router"
	"github.com/yu/iot-platform-go/service"
	"github.com/yu/iot-platform-go/websocket"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp Wire 依赖注入入口 — 自动解析依赖关系，生成 wire_gen.go
func InitializeApp(db *gorm.DB, rdb *redis.Client) (*AppComponents, error) {
	userRepo := repository.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	deviceRepo := repository.NewDeviceRepo(db)
	redisCache := cache.NewRedisCache(rdb)
	deviceService := service.NewDeviceService(deviceRepo, redisCache)
	influxDBService := provideInfluxDBService()
	deviceReportService := service.NewDeviceReportService(deviceRepo, influxDBService, redisCache, deviceService)
	mqttPublishLogRepo := repository.NewMqttPublishLogRepo(db)
	downlinkCmdRepo := repository.NewDownlinkCmdRepo(db)
	hub := websocket.NewHub()
	mqttClientService := service.NewMqttClientService(mqttPublishLogRepo, redisCache, hub)
	mqttPublishLogService := service.NewMqttPublishLogService(mqttPublishLogRepo)
	downlinkService := service.NewDownlinkService(downlinkCmdRepo, deviceRepo, rdb, hub)
	services := provideRouterServices(userService, deviceService, deviceReportService, influxDBService, mqttClientService, mqttPublishLogService, downlinkService)
	wsHandler := websocket.NewWsHandler(hub, mqttClientService)
	appComponents := &AppComponents{
		Services:  services,
		WsHandler: wsHandler,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents Wire 聚合结构体（用于多返回值注入）
type AppComponents struct {
	Services  *router.Services
	WsHandler *websocket.WsHandler
}

// provideInfluxDBService 提供 InfluxDB 服务（4 个 string 参数需手动注入）
func provideInfluxDBService() *service.InfluxDBService {
	cfg := config.Cfg
	return service.NewInfluxDBService(cfg.InfluxDB.URL, cfg.InfluxDB.Token, cfg.InfluxDB.Org, cfg.InfluxDB.Bucket)
}

// provideRouterServices 聚合所有 Service 到 router.Services
func provideRouterServices(
	userSvc *service.UserService,
	deviceSvc *service.DeviceService,
	reportSvc *service.DeviceReportService,
	influxSvc *service.InfluxDBService,
	mqttSvc *service.MqttClientService,
	mqttLogSvc *service.MqttPublishLogService,
	downlinkSvc *service.DownlinkService,
) *router.Services {
	return &router.Services{
		User:     userSvc,
		Device:   deviceSvc,
		Report:   reportSvc,
		InfluxDB: influxSvc,
		MQTT:     mqttSvc,
		MQTTLog:  mqttLogSvc,
		Downlink: downlinkSvc,
	}
}
