// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/redis/go-redis/v9"
	"github.com/yu/iot-platform-go/internal/ent"
	"github.com/yu/iot-platform-go/internal/repository"
	"github.com/yu/iot-platform-go/internal/router"
	"github.com/yu/iot-platform-go/internal/service"
	"github.com/yu/iot-platform-go/internal/websocket"
	"github.com/yu/iot-platform-go/pkg/cache"
	"github.com/yu/iot-platform-go/pkg/config"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp Wire 依赖注入入口
func InitializeApp(entClient *ent.Client, rdb *redis.Client) (*AppComponents, error) {
	userRepo := repository.NewUserRepo(entClient)
	userService := service.NewUserService(userRepo)
	deviceRepo := repository.NewDeviceRepo(entClient)
	redisCache := cache.NewRedisCache(rdb)
	deviceService := service.NewDeviceService(deviceRepo, redisCache)
	influxDBService := provideInfluxDBService()
	deviceReportService := service.NewDeviceReportService(deviceRepo, influxDBService, redisCache, deviceService)
	mqttPublishLogRepo := repository.NewMqttPublishLogRepo(entClient)
	hub := websocket.NewHub()
	mqttClientService := service.NewMqttClientService(mqttPublishLogRepo, redisCache, hub)
	mqttPublishLogService := service.NewMqttPublishLogService(mqttPublishLogRepo)
	downlinkCmdRepo := repository.NewDownlinkCmdRepo(entClient)
	downlinkService := service.NewDownlinkService(downlinkCmdRepo, deviceRepo, rdb, hub)
	services := provideRouterServices(userService, deviceService, deviceReportService, influxDBService, mqttClientService, mqttPublishLogService, downlinkService)
	wsHandler := websocket.NewWsHandler(hub, mqttClientService)
	appComponents := &AppComponents{
		Services:  services,
		WsHandler: wsHandler,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents Wire 聚合结构体
type AppComponents struct {
	Services  *router.Services
	WsHandler *websocket.WsHandler
}

func provideInfluxDBService() *service.InfluxDBService {
	cfg := config.Cfg
	return service.NewInfluxDBService(cfg.InfluxDB.URL, cfg.InfluxDB.Token, cfg.InfluxDB.Org, cfg.InfluxDB.Bucket)
}

func provideRouterServices(
	userSvc *service.UserService,
	deviceSvc *service.DeviceService,
	reportSvc *service.DeviceReportService,
	influxSvc *service.InfluxDBService,
	mqttSvc *service.MqttClientService,
	mqttLogSvc *service.MqttPublishLogService,
	downlinkSvc *service.DownlinkService,
) *router.Services {
	return &router.Services{
		User:     userSvc,
		Device:   deviceSvc,
		Report:   reportSvc,
		InfluxDB: influxSvc,
		MQTT:     mqttSvc,
		MQTTLog:  mqttLogSvc,
		Downlink: downlinkSvc,
	}
}
