// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/redis/go-redis/v9"
	"iot-platform.local/internal/ent"
	"iot-platform.local/internal/mqtt"
	"iot-platform.local/internal/repository"
	"iot-platform.local/internal/router"
	"iot-platform.local/internal/service"
	"iot-platform.local/internal/websocket"
	"iot-platform.local/pkg/cache"
	"iot-platform.local/pkg/config"
	"time"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp Wire 依赖注入入口
func InitializeApp(entClient *ent.Client, rdb *redis.Client) (*AppComponents, error) {
	userRepo := repository.NewUserRepo(entClient)
	redisCache := cache.NewRedisCache(rdb)
	userService := service.NewUserService(userRepo, redisCache)
	deviceRepo := repository.NewDeviceRepo(entClient)
	deviceThingRepo := repository.NewDeviceThingRepo(entClient)
	deviceConfigRepo := repository.NewDeviceConfigRepo(entClient)
	deviceService := service.NewDeviceService(deviceRepo, redisCache, deviceThingRepo, deviceConfigRepo)
	influxDBService := provideInfluxDBService(redisCache)
	deviceReportService := service.NewDeviceReportService(deviceRepo, influxDBService, redisCache, deviceService)
	messageLogRepo := repository.NewMessageLogRepo(entClient)
	hub := websocket.NewHub()
	mqttPublisher := provideMqttPublisher()
	downlinkService := service.NewDownlinkService(messageLogRepo, deviceRepo, rdb, hub, mqttPublisher)
	deviceConfigService := service.NewDeviceConfigService(deviceConfigRepo, downlinkService, mqttPublisher)
	deviceSensorService := service.NewDeviceSensorService(deviceThingRepo, deviceConfigService, redisCache)
	deviceActuatorService := service.NewDeviceActuatorService(deviceThingRepo, deviceConfigService, redisCache)
	services := provideRouterServices(userService, deviceService, deviceReportService, influxDBService, downlinkService, deviceConfigService, deviceSensorService, deviceActuatorService)
	wsHandler := websocket.NewWsHandler(hub)
	appComponents := &AppComponents{
		Services:  services,
		WsHandler: wsHandler,
		Cache:     redisCache,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents Wire 聚合结构体
type AppComponents struct {
	Services  *router.Services
	WsHandler *websocket.WsHandler
	Cache     *cache.RedisCache
}

func provideInfluxDBService(redisCache *cache.RedisCache) *service.InfluxDBService {
	cfg := config.Cfg
	maxIdleConns := cfg.InfluxDB.MaxIdleConnections
	if maxIdleConns <= 0 {
		maxIdleConns = 50
	}
	return service.NewInfluxDBService(service.InfluxDBConfig{
		URL:                   cfg.InfluxDB.URL,
		Token:                 cfg.InfluxDB.Token,
		Database:              cfg.InfluxDB.Database,
		AuthScheme:            cfg.InfluxDB.AuthScheme,
		WriteTimeout:          10 * time.Second,
		QueryTimeout:          2 * time.Minute,
		IdleConnectionTimeout: 90 * time.Second,
		MaxIdleConnections:    maxIdleConns,
	}, redisCache)
}

// provideMqttPublisher MQTT 下行发布器：网关未启用（Broker 不可达）时返回 nil，
// 各服务将仅走 HTTP/WS/命令队列通道。wire 注入单实例供多个服务共享。
func provideMqttPublisher() service.MqttPublisher {
	if !config.Cfg.MqttGateway.Enabled {
		return nil
	}
	return mqtt.NewPublisher()
}

func provideRouterServices(
	userSvc *service.UserService,
	deviceSvc *service.DeviceService,
	reportSvc *service.DeviceReportService,
	influxSvc *service.InfluxDBService,
	downlinkSvc *service.DownlinkService,
	configSvc *service.DeviceConfigService,
	sensorSvc *service.DeviceSensorService,
	actuatorSvc *service.DeviceActuatorService,
) *router.Services {
	return &router.Services{
		User:      userSvc,
		Device:    deviceSvc,
		Report:    reportSvc,
		InfluxDB:  influxSvc,
		Downlink:  downlinkSvc,
		Config:    configSvc,
		Sensors:   sensorSvc,
		Actuators: actuatorSvc,
	}
}
