// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "device_id", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "device_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "device_type", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "firmware_version", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Size: 45, Default: ""},
		{Name: "mac_address", Type: field.TypeString, Size: 17, Default: ""},
		{Name: "location", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "owner_id", Type: field.TypeUint, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 50, Default: "OFFLINE"},
		{Name: "last_active_time", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "device_device_id",
				Unique:  true,
				Columns: []*schema.Column{DevicesColumns[1]},
			},
		},
	}
	// DownlinkCmdsColumns holds the columns for the "downlink_cmds" table.
	DownlinkCmdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "device_id", Type: field.TypeString, Size: 50},
		{Name: "type", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "payload", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DownlinkCmdsTable holds the schema information for the "downlink_cmds" table.
	DownlinkCmdsTable = &schema.Table{
		Name:       "downlink_cmds",
		Columns:    DownlinkCmdsColumns,
		PrimaryKey: []*schema.Column{DownlinkCmdsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "downlinkcmd_device_id",
				Unique:  false,
				Columns: []*schema.Column{DownlinkCmdsColumns[1]},
			},
		},
	}
	// MqttPublishLogsColumns holds the columns for the "mqtt_publish_logs" table.
	MqttPublishLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "topic", Type: field.TypeString, Size: 255},
		{Name: "payload", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "qos", Type: field.TypeInt, Default: 0},
		{Name: "retained", Type: field.TypeBool, Default: false},
		{Name: "client_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "broker_url", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "create_time", Type: field.TypeTime},
	}
	// MqttPublishLogsTable holds the schema information for the "mqtt_publish_logs" table.
	MqttPublishLogsTable = &schema.Table{
		Name:       "mqtt_publish_logs",
		Columns:    MqttPublishLogsColumns,
		PrimaryKey: []*schema.Column{MqttPublishLogsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "age", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "account", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "passwd", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 50, Default: "user"},
		{Name: "status", Type: field.TypeString, Size: 50, Default: "active"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_account",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		DownlinkCmdsTable,
		MqttPublishLogsTable,
		UsersTable,
	}
)

func init() {
}
