// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/yu/iot-platform-go/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/yu/iot-platform-go/internal/ent/device"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
	"github.com/yu/iot-platform-go/internal/ent/mqttpublishlog"
	"github.com/yu/iot-platform-go/internal/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Device is the client for interacting with the Device builders.
	Device *DeviceClient
	// DownlinkCmd is the client for interacting with the DownlinkCmd builders.
	DownlinkCmd *DownlinkCmdClient
	// MqttPublishLog is the client for interacting with the MqttPublishLog builders.
	MqttPublishLog *MqttPublishLogClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Device = NewDeviceClient(c.config)
	c.DownlinkCmd = NewDownlinkCmdClient(c.config)
	c.MqttPublishLog = NewMqttPublishLogClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Device:         NewDeviceClient(cfg),
		DownlinkCmd:    NewDownlinkCmdClient(cfg),
		MqttPublishLog: NewMqttPublishLogClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Device:         NewDeviceClient(cfg),
		DownlinkCmd:    NewDownlinkCmdClient(cfg),
		MqttPublishLog: NewMqttPublishLogClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Device.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Device.Use(hooks...)
	c.DownlinkCmd.Use(hooks...)
	c.MqttPublishLog.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Device.Intercept(interceptors...)
	c.DownlinkCmd.Intercept(interceptors...)
	c.MqttPublishLog.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DeviceMutation:
		return c.Device.mutate(ctx, m)
	case *DownlinkCmdMutation:
		return c.DownlinkCmd.mutate(ctx, m)
	case *MqttPublishLogMutation:
		return c.MqttPublishLog.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DeviceClient is a client for the Device schema.
type DeviceClient struct {
	config
}

// NewDeviceClient returns a client for the Device from the given config.
func NewDeviceClient(c config) *DeviceClient {
	return &DeviceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `device.Hooks(f(g(h())))`.
func (c *DeviceClient) Use(hooks ...Hook) {
	c.hooks.Device = append(c.hooks.Device, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `device.Intercept(f(g(h())))`.
func (c *DeviceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Device = append(c.inters.Device, interceptors...)
}

// Create returns a builder for creating a Device entity.
func (c *DeviceClient) Create() *DeviceCreate {
	mutation := newDeviceMutation(c.config, OpCreate)
	return &DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Device entities.
func (c *DeviceClient) CreateBulk(builders ...*DeviceCreate) *DeviceCreateBulk {
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceClient) MapCreateBulk(slice any, setFunc func(*DeviceCreate, int)) *DeviceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceCreateBulk{err: fmt.Errorf("calling to DeviceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Device.
func (c *DeviceClient) Update() *DeviceUpdate {
	mutation := newDeviceMutation(c.config, OpUpdate)
	return &DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceClient) UpdateOne(_m *Device) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDevice(_m))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceClient) UpdateOneID(id uint) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDeviceID(id))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Device.
func (c *DeviceClient) Delete() *DeviceDelete {
	mutation := newDeviceMutation(c.config, OpDelete)
	return &DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceClient) DeleteOne(_m *Device) *DeviceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceClient) DeleteOneID(id uint) *DeviceDeleteOne {
	builder := c.Delete().Where(device.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceDeleteOne{builder}
}

// Query returns a query builder for Device.
func (c *DeviceClient) Query() *DeviceQuery {
	return &DeviceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevice},
		inters: c.Interceptors(),
	}
}

// Get returns a Device entity by its id.
func (c *DeviceClient) Get(ctx context.Context, id uint) (*Device, error) {
	return c.Query().Where(device.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceClient) GetX(ctx context.Context, id uint) *Device {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceClient) Hooks() []Hook {
	return c.hooks.Device
}

// Interceptors returns the client interceptors.
func (c *DeviceClient) Interceptors() []Interceptor {
	return c.inters.Device
}

func (c *DeviceClient) mutate(ctx context.Context, m *DeviceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Device mutation op: %q", m.Op())
	}
}

// DownlinkCmdClient is a client for the DownlinkCmd schema.
type DownlinkCmdClient struct {
	config
}

// NewDownlinkCmdClient returns a client for the DownlinkCmd from the given config.
func NewDownlinkCmdClient(c config) *DownlinkCmdClient {
	return &DownlinkCmdClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `downlinkcmd.Hooks(f(g(h())))`.
func (c *DownlinkCmdClient) Use(hooks ...Hook) {
	c.hooks.DownlinkCmd = append(c.hooks.DownlinkCmd, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `downlinkcmd.Intercept(f(g(h())))`.
func (c *DownlinkCmdClient) Intercept(interceptors ...Interceptor) {
	c.inters.DownlinkCmd = append(c.inters.DownlinkCmd, interceptors...)
}

// Create returns a builder for creating a DownlinkCmd entity.
func (c *DownlinkCmdClient) Create() *DownlinkCmdCreate {
	mutation := newDownlinkCmdMutation(c.config, OpCreate)
	return &DownlinkCmdCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DownlinkCmd entities.
func (c *DownlinkCmdClient) CreateBulk(builders ...*DownlinkCmdCreate) *DownlinkCmdCreateBulk {
	return &DownlinkCmdCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DownlinkCmdClient) MapCreateBulk(slice any, setFunc func(*DownlinkCmdCreate, int)) *DownlinkCmdCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DownlinkCmdCreateBulk{err: fmt.Errorf("calling to DownlinkCmdClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DownlinkCmdCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DownlinkCmdCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DownlinkCmd.
func (c *DownlinkCmdClient) Update() *DownlinkCmdUpdate {
	mutation := newDownlinkCmdMutation(c.config, OpUpdate)
	return &DownlinkCmdUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DownlinkCmdClient) UpdateOne(_m *DownlinkCmd) *DownlinkCmdUpdateOne {
	mutation := newDownlinkCmdMutation(c.config, OpUpdateOne, withDownlinkCmd(_m))
	return &DownlinkCmdUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DownlinkCmdClient) UpdateOneID(id uint) *DownlinkCmdUpdateOne {
	mutation := newDownlinkCmdMutation(c.config, OpUpdateOne, withDownlinkCmdID(id))
	return &DownlinkCmdUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DownlinkCmd.
func (c *DownlinkCmdClient) Delete() *DownlinkCmdDelete {
	mutation := newDownlinkCmdMutation(c.config, OpDelete)
	return &DownlinkCmdDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DownlinkCmdClient) DeleteOne(_m *DownlinkCmd) *DownlinkCmdDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DownlinkCmdClient) DeleteOneID(id uint) *DownlinkCmdDeleteOne {
	builder := c.Delete().Where(downlinkcmd.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DownlinkCmdDeleteOne{builder}
}

// Query returns a query builder for DownlinkCmd.
func (c *DownlinkCmdClient) Query() *DownlinkCmdQuery {
	return &DownlinkCmdQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDownlinkCmd},
		inters: c.Interceptors(),
	}
}

// Get returns a DownlinkCmd entity by its id.
func (c *DownlinkCmdClient) Get(ctx context.Context, id uint) (*DownlinkCmd, error) {
	return c.Query().Where(downlinkcmd.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DownlinkCmdClient) GetX(ctx context.Context, id uint) *DownlinkCmd {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DownlinkCmdClient) Hooks() []Hook {
	return c.hooks.DownlinkCmd
}

// Interceptors returns the client interceptors.
func (c *DownlinkCmdClient) Interceptors() []Interceptor {
	return c.inters.DownlinkCmd
}

func (c *DownlinkCmdClient) mutate(ctx context.Context, m *DownlinkCmdMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DownlinkCmdCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DownlinkCmdUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DownlinkCmdUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DownlinkCmdDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DownlinkCmd mutation op: %q", m.Op())
	}
}

// MqttPublishLogClient is a client for the MqttPublishLog schema.
type MqttPublishLogClient struct {
	config
}

// NewMqttPublishLogClient returns a client for the MqttPublishLog from the given config.
func NewMqttPublishLogClient(c config) *MqttPublishLogClient {
	return &MqttPublishLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mqttpublishlog.Hooks(f(g(h())))`.
func (c *MqttPublishLogClient) Use(hooks ...Hook) {
	c.hooks.MqttPublishLog = append(c.hooks.MqttPublishLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mqttpublishlog.Intercept(f(g(h())))`.
func (c *MqttPublishLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.MqttPublishLog = append(c.inters.MqttPublishLog, interceptors...)
}

// Create returns a builder for creating a MqttPublishLog entity.
func (c *MqttPublishLogClient) Create() *MqttPublishLogCreate {
	mutation := newMqttPublishLogMutation(c.config, OpCreate)
	return &MqttPublishLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MqttPublishLog entities.
func (c *MqttPublishLogClient) CreateBulk(builders ...*MqttPublishLogCreate) *MqttPublishLogCreateBulk {
	return &MqttPublishLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MqttPublishLogClient) MapCreateBulk(slice any, setFunc func(*MqttPublishLogCreate, int)) *MqttPublishLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MqttPublishLogCreateBulk{err: fmt.Errorf("calling to MqttPublishLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MqttPublishLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MqttPublishLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MqttPublishLog.
func (c *MqttPublishLogClient) Update() *MqttPublishLogUpdate {
	mutation := newMqttPublishLogMutation(c.config, OpUpdate)
	return &MqttPublishLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MqttPublishLogClient) UpdateOne(_m *MqttPublishLog) *MqttPublishLogUpdateOne {
	mutation := newMqttPublishLogMutation(c.config, OpUpdateOne, withMqttPublishLog(_m))
	return &MqttPublishLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MqttPublishLogClient) UpdateOneID(id uint) *MqttPublishLogUpdateOne {
	mutation := newMqttPublishLogMutation(c.config, OpUpdateOne, withMqttPublishLogID(id))
	return &MqttPublishLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MqttPublishLog.
func (c *MqttPublishLogClient) Delete() *MqttPublishLogDelete {
	mutation := newMqttPublishLogMutation(c.config, OpDelete)
	return &MqttPublishLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MqttPublishLogClient) DeleteOne(_m *MqttPublishLog) *MqttPublishLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MqttPublishLogClient) DeleteOneID(id uint) *MqttPublishLogDeleteOne {
	builder := c.Delete().Where(mqttpublishlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MqttPublishLogDeleteOne{builder}
}

// Query returns a query builder for MqttPublishLog.
func (c *MqttPublishLogClient) Query() *MqttPublishLogQuery {
	return &MqttPublishLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMqttPublishLog},
		inters: c.Interceptors(),
	}
}

// Get returns a MqttPublishLog entity by its id.
func (c *MqttPublishLogClient) Get(ctx context.Context, id uint) (*MqttPublishLog, error) {
	return c.Query().Where(mqttpublishlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MqttPublishLogClient) GetX(ctx context.Context, id uint) *MqttPublishLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MqttPublishLogClient) Hooks() []Hook {
	return c.hooks.MqttPublishLog
}

// Interceptors returns the client interceptors.
func (c *MqttPublishLogClient) Interceptors() []Interceptor {
	return c.inters.MqttPublishLog
}

func (c *MqttPublishLogClient) mutate(ctx context.Context, m *MqttPublishLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MqttPublishLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MqttPublishLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MqttPublishLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MqttPublishLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MqttPublishLog mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uint) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uint) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uint) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uint) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Device, DownlinkCmd, MqttPublishLog, User []ent.Hook
	}
	inters struct {
		Device, DownlinkCmd, MqttPublishLog, User []ent.Interceptor
	}
)
