// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/device"
	"github.com/yu/iot-platform-go/internal/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdate) SetDeviceID(v string) *DeviceUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdate) SetDeviceName(v string) *DeviceUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *DeviceUpdate) SetDeviceType(v string) *DeviceUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceType(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdate) SetFirmwareVersion(v string) *DeviceUpdate {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableFirmwareVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *DeviceUpdate) SetIPAddress(v string) *DeviceUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIPAddress(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetMACAddress sets the "mac_address" field.
func (_u *DeviceUpdate) SetMACAddress(v string) *DeviceUpdate {
	_u.mutation.SetMACAddress(v)
	return _u
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableMACAddress(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetMACAddress(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *DeviceUpdate) SetLocation(v string) *DeviceUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLocation(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DeviceUpdate) SetOwnerID(v uint) *DeviceUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOwnerID(v *uint) *DeviceUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *DeviceUpdate) AddOwnerID(v int) *DeviceUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdate) SetStatus(v string) *DeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableStatus(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastActiveTime sets the "last_active_time" field.
func (_u *DeviceUpdate) SetLastActiveTime(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastActiveTime(v)
	return _u
}

// SetNillableLastActiveTime sets the "last_active_time" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastActiveTime(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastActiveTime(*v)
	}
	return _u
}

// ClearLastActiveTime clears the value of the "last_active_time" field.
func (_u *DeviceUpdate) ClearLastActiveTime() *DeviceUpdate {
	_u.mutation.ClearLastActiveTime()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdate) SetCreatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableCreatedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirmwareVersion(); ok {
		if err := device.FirmwareVersionValidator(v); err != nil {
			return &ValidationError{Name: "firmware_version", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := device.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "Device.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MACAddress(); ok {
		if err := device.MACAddressValidator(v); err != nil {
			return &ValidationError{Name: "mac_address", err: fmt.Errorf(`ent: validator failed for field "Device.mac_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := device.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Device.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(device.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.MACAddress(); ok {
		_spec.SetField(device.FieldMACAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(device.FieldOwnerID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(device.FieldOwnerID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActiveTime(); ok {
		_spec.SetField(device.FieldLastActiveTime, field.TypeTime, value)
	}
	if _u.mutation.LastActiveTimeCleared() {
		_spec.ClearField(device.FieldLastActiveTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdateOne) SetDeviceID(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdateOne) SetDeviceName(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *DeviceUpdateOne) SetDeviceType(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceType(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdateOne) SetFirmwareVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableFirmwareVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *DeviceUpdateOne) SetIPAddress(v string) *DeviceUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIPAddress(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetMACAddress sets the "mac_address" field.
func (_u *DeviceUpdateOne) SetMACAddress(v string) *DeviceUpdateOne {
	_u.mutation.SetMACAddress(v)
	return _u
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableMACAddress(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetMACAddress(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *DeviceUpdateOne) SetLocation(v string) *DeviceUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLocation(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DeviceUpdateOne) SetOwnerID(v uint) *DeviceUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOwnerID(v *uint) *DeviceUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *DeviceUpdateOne) AddOwnerID(v int) *DeviceUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdateOne) SetStatus(v string) *DeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableStatus(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastActiveTime sets the "last_active_time" field.
func (_u *DeviceUpdateOne) SetLastActiveTime(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastActiveTime(v)
	return _u
}

// SetNillableLastActiveTime sets the "last_active_time" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastActiveTime(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastActiveTime(*v)
	}
	return _u
}

// ClearLastActiveTime clears the value of the "last_active_time" field.
func (_u *DeviceUpdateOne) ClearLastActiveTime() *DeviceUpdateOne {
	_u.mutation.ClearLastActiveTime()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdateOne) SetCreatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableCreatedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirmwareVersion(); ok {
		if err := device.FirmwareVersionValidator(v); err != nil {
			return &ValidationError{Name: "firmware_version", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := device.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "Device.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MACAddress(); ok {
		if err := device.MACAddressValidator(v); err != nil {
			return &ValidationError{Name: "mac_address", err: fmt.Errorf(`ent: validator failed for field "Device.mac_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := device.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Device.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(device.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.MACAddress(); ok {
		_spec.SetField(device.FieldMACAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(device.FieldOwnerID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(device.FieldOwnerID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActiveTime(); ok {
		_spec.SetField(device.FieldLastActiveTime, field.TypeTime, value)
	}
	if _u.mutation.LastActiveTimeCleared() {
		_spec.ClearField(device.FieldLastActiveTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
