// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/device"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceCreate) SetDeviceID(v string) *DeviceCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *DeviceCreate) SetDeviceName(v string) *DeviceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceName(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *DeviceCreate) SetDeviceType(v string) *DeviceCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceType(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceType(*v)
	}
	return _c
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_c *DeviceCreate) SetFirmwareVersion(v string) *DeviceCreate {
	_c.mutation.SetFirmwareVersion(v)
	return _c
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableFirmwareVersion(v *string) *DeviceCreate {
	if v != nil {
		_c.SetFirmwareVersion(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *DeviceCreate) SetIPAddress(v string) *DeviceCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableIPAddress(v *string) *DeviceCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetMACAddress sets the "mac_address" field.
func (_c *DeviceCreate) SetMACAddress(v string) *DeviceCreate {
	_c.mutation.SetMACAddress(v)
	return _c
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableMACAddress(v *string) *DeviceCreate {
	if v != nil {
		_c.SetMACAddress(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *DeviceCreate) SetLocation(v string) *DeviceCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLocation(v *string) *DeviceCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *DeviceCreate) SetOwnerID(v uint) *DeviceCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableOwnerID(v *uint) *DeviceCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeviceCreate) SetStatus(v string) *DeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableStatus(v *string) *DeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastActiveTime sets the "last_active_time" field.
func (_c *DeviceCreate) SetLastActiveTime(v time.Time) *DeviceCreate {
	_c.mutation.SetLastActiveTime(v)
	return _c
}

// SetNillableLastActiveTime sets the "last_active_time" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLastActiveTime(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetLastActiveTime(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceCreate) SetID(v uint) *DeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := device.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		v := device.DefaultDeviceType
		_c.mutation.SetDeviceType(v)
	}
	if _, ok := _c.mutation.FirmwareVersion(); !ok {
		v := device.DefaultFirmwareVersion
		_c.mutation.SetFirmwareVersion(v)
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := device.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.MACAddress(); !ok {
		v := device.DefaultMACAddress
		_c.mutation.SetMACAddress(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := device.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		v := device.DefaultOwnerID
		_c.mutation.SetOwnerID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := device.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "Device.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "Device.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "Device.device_type"`)}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirmwareVersion(); !ok {
		return &ValidationError{Name: "firmware_version", err: errors.New(`ent: missing required field "Device.firmware_version"`)}
	}
	if v, ok := _c.mutation.FirmwareVersion(); ok {
		if err := device.FirmwareVersionValidator(v); err != nil {
			return &ValidationError{Name: "firmware_version", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "Device.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := device.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "Device.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MACAddress(); !ok {
		return &ValidationError{Name: "mac_address", err: errors.New(`ent: missing required field "Device.mac_address"`)}
	}
	if v, ok := _c.mutation.MACAddress(); ok {
		if err := device.MACAddressValidator(v); err != nil {
			return &ValidationError{Name: "mac_address", err: fmt.Errorf(`ent: validator failed for field "Device.mac_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Device.location"`)}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := device.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Device.location": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Device.owner_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Device.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
		_node.FirmwareVersion = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(device.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.MACAddress(); ok {
		_spec.SetField(device.FieldMACAddress, field.TypeString, value)
		_node.MACAddress = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(device.FieldOwnerID, field.TypeUint, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastActiveTime(); ok {
		_spec.SetField(device.FieldLastActiveTime, field.TypeTime, value)
		_node.LastActiveTime = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
