// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
	"github.com/yu/iot-platform-go/internal/ent/predicate"
)

// DownlinkCmdUpdate is the builder for updating DownlinkCmd entities.
type DownlinkCmdUpdate struct {
	config
	hooks    []Hook
	mutation *DownlinkCmdMutation
}

// Where appends a list predicates to the DownlinkCmdUpdate builder.
func (_u *DownlinkCmdUpdate) Where(ps ...predicate.DownlinkCmd) *DownlinkCmdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DownlinkCmdUpdate) SetDeviceID(v string) *DownlinkCmdUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DownlinkCmdUpdate) SetNillableDeviceID(v *string) *DownlinkCmdUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DownlinkCmdUpdate) SetType(v string) *DownlinkCmdUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DownlinkCmdUpdate) SetNillableType(v *string) *DownlinkCmdUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DownlinkCmdUpdate) SetPayload(v string) *DownlinkCmdUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DownlinkCmdUpdate) SetNillablePayload(v *string) *DownlinkCmdUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DownlinkCmdUpdate) SetStatus(v string) *DownlinkCmdUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DownlinkCmdUpdate) SetNillableStatus(v *string) *DownlinkCmdUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DownlinkCmdUpdate) SetCreatedAt(v time.Time) *DownlinkCmdUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DownlinkCmdUpdate) SetNillableCreatedAt(v *time.Time) *DownlinkCmdUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DownlinkCmdMutation object of the builder.
func (_u *DownlinkCmdUpdate) Mutation() *DownlinkCmdMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DownlinkCmdUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownlinkCmdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DownlinkCmdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownlinkCmdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownlinkCmdUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := downlinkcmd.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := downlinkcmd.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := downlinkcmd.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DownlinkCmdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downlinkcmd.Table, downlinkcmd.Columns, sqlgraph.NewFieldSpec(downlinkcmd.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(downlinkcmd.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(downlinkcmd.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(downlinkcmd.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(downlinkcmd.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(downlinkcmd.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downlinkcmd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DownlinkCmdUpdateOne is the builder for updating a single DownlinkCmd entity.
type DownlinkCmdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DownlinkCmdMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *DownlinkCmdUpdateOne) SetDeviceID(v string) *DownlinkCmdUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DownlinkCmdUpdateOne) SetNillableDeviceID(v *string) *DownlinkCmdUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DownlinkCmdUpdateOne) SetType(v string) *DownlinkCmdUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DownlinkCmdUpdateOne) SetNillableType(v *string) *DownlinkCmdUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DownlinkCmdUpdateOne) SetPayload(v string) *DownlinkCmdUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DownlinkCmdUpdateOne) SetNillablePayload(v *string) *DownlinkCmdUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DownlinkCmdUpdateOne) SetStatus(v string) *DownlinkCmdUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DownlinkCmdUpdateOne) SetNillableStatus(v *string) *DownlinkCmdUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DownlinkCmdUpdateOne) SetCreatedAt(v time.Time) *DownlinkCmdUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DownlinkCmdUpdateOne) SetNillableCreatedAt(v *time.Time) *DownlinkCmdUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DownlinkCmdMutation object of the builder.
func (_u *DownlinkCmdUpdateOne) Mutation() *DownlinkCmdMutation {
	return _u.mutation
}

// Where appends a list predicates to the DownlinkCmdUpdate builder.
func (_u *DownlinkCmdUpdateOne) Where(ps ...predicate.DownlinkCmd) *DownlinkCmdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DownlinkCmdUpdateOne) Select(field string, fields ...string) *DownlinkCmdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DownlinkCmd entity.
func (_u *DownlinkCmdUpdateOne) Save(ctx context.Context) (*DownlinkCmd, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownlinkCmdUpdateOne) SaveX(ctx context.Context) *DownlinkCmd {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DownlinkCmdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownlinkCmdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownlinkCmdUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := downlinkcmd.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := downlinkcmd.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := downlinkcmd.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DownlinkCmdUpdateOne) sqlSave(ctx context.Context) (_node *DownlinkCmd, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downlinkcmd.Table, downlinkcmd.Columns, sqlgraph.NewFieldSpec(downlinkcmd.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DownlinkCmd.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, downlinkcmd.FieldID)
		for _, f := range fields {
			if !downlinkcmd.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != downlinkcmd.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(downlinkcmd.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(downlinkcmd.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(downlinkcmd.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(downlinkcmd.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(downlinkcmd.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &DownlinkCmd{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downlinkcmd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
