// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
)

// DownlinkCmd is the model entity for the DownlinkCmd schema.
type DownlinkCmd struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"deviceId"`
	// Type holds the value of the "type" field.
	Type string `json:"type"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"-"`
	// Status holds the value of the "status" field.
	Status string `json:"status"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"createdAt"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DownlinkCmd) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case downlinkcmd.FieldID:
			values[i] = new(sql.NullInt64)
		case downlinkcmd.FieldDeviceID, downlinkcmd.FieldType, downlinkcmd.FieldPayload, downlinkcmd.FieldStatus:
			values[i] = new(sql.NullString)
		case downlinkcmd.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DownlinkCmd fields.
func (_m *DownlinkCmd) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case downlinkcmd.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case downlinkcmd.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case downlinkcmd.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case downlinkcmd.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case downlinkcmd.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case downlinkcmd.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DownlinkCmd.
// This includes values selected through modifiers, order, etc.
func (_m *DownlinkCmd) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DownlinkCmd.
// Note that you need to call DownlinkCmd.Unwrap() before calling this method if this DownlinkCmd
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DownlinkCmd) Update() *DownlinkCmdUpdateOne {
	return NewDownlinkCmdClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DownlinkCmd entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DownlinkCmd) Unwrap() *DownlinkCmd {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DownlinkCmd is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DownlinkCmd) String() string {
	var builder strings.Builder
	builder.WriteString("DownlinkCmd(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DownlinkCmds is a parsable slice of DownlinkCmd.
type DownlinkCmds []*DownlinkCmd
