// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
)

// DownlinkCmdCreate is the builder for creating a DownlinkCmd entity.
type DownlinkCmdCreate struct {
	config
	mutation *DownlinkCmdMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DownlinkCmdCreate) SetDeviceID(v string) *DownlinkCmdCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *DownlinkCmdCreate) SetType(v string) *DownlinkCmdCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *DownlinkCmdCreate) SetNillableType(v *string) *DownlinkCmdCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *DownlinkCmdCreate) SetPayload(v string) *DownlinkCmdCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *DownlinkCmdCreate) SetNillablePayload(v *string) *DownlinkCmdCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DownlinkCmdCreate) SetStatus(v string) *DownlinkCmdCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DownlinkCmdCreate) SetNillableStatus(v *string) *DownlinkCmdCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DownlinkCmdCreate) SetCreatedAt(v time.Time) *DownlinkCmdCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DownlinkCmdCreate) SetNillableCreatedAt(v *time.Time) *DownlinkCmdCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DownlinkCmdCreate) SetID(v uint) *DownlinkCmdCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DownlinkCmdMutation object of the builder.
func (_c *DownlinkCmdCreate) Mutation() *DownlinkCmdMutation {
	return _c.mutation
}

// Save creates the DownlinkCmd in the database.
func (_c *DownlinkCmdCreate) Save(ctx context.Context) (*DownlinkCmd, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DownlinkCmdCreate) SaveX(ctx context.Context) *DownlinkCmd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownlinkCmdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownlinkCmdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DownlinkCmdCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := downlinkcmd.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := downlinkcmd.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := downlinkcmd.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := downlinkcmd.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DownlinkCmdCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DownlinkCmd.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := downlinkcmd.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "DownlinkCmd.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := downlinkcmd.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "DownlinkCmd.payload"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DownlinkCmd.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := downlinkcmd.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownlinkCmd.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DownlinkCmd.created_at"`)}
	}
	return nil
}

func (_c *DownlinkCmdCreate) sqlSave(ctx context.Context) (*DownlinkCmd, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DownlinkCmdCreate) createSpec() (*DownlinkCmd, *sqlgraph.CreateSpec) {
	var (
		_node = &DownlinkCmd{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(downlinkcmd.Table, sqlgraph.NewFieldSpec(downlinkcmd.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(downlinkcmd.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(downlinkcmd.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(downlinkcmd.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(downlinkcmd.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(downlinkcmd.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DownlinkCmdCreateBulk is the builder for creating many DownlinkCmd entities in bulk.
type DownlinkCmdCreateBulk struct {
	config
	err      error
	builders []*DownlinkCmdCreate
}

// Save creates the DownlinkCmd entities in the database.
func (_c *DownlinkCmdCreateBulk) Save(ctx context.Context) ([]*DownlinkCmd, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DownlinkCmd, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DownlinkCmdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DownlinkCmdCreateBulk) SaveX(ctx context.Context) []*DownlinkCmd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownlinkCmdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownlinkCmdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
