// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
	"github.com/yu/iot-platform-go/internal/ent/predicate"
)

// DownlinkCmdDelete is the builder for deleting a DownlinkCmd entity.
type DownlinkCmdDelete struct {
	config
	hooks    []Hook
	mutation *DownlinkCmdMutation
}

// Where appends a list predicates to the DownlinkCmdDelete builder.
func (_d *DownlinkCmdDelete) Where(ps ...predicate.DownlinkCmd) *DownlinkCmdDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DownlinkCmdDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DownlinkCmdDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DownlinkCmdDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(downlinkcmd.Table, sqlgraph.NewFieldSpec(downlinkcmd.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DownlinkCmdDeleteOne is the builder for deleting a single DownlinkCmd entity.
type DownlinkCmdDeleteOne struct {
	_d *DownlinkCmdDelete
}

// Where appends a list predicates to the DownlinkCmdDelete builder.
func (_d *DownlinkCmdDeleteOne) Where(ps ...predicate.DownlinkCmd) *DownlinkCmdDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DownlinkCmdDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{downlinkcmd.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DownlinkCmdDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
