// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yu/iot-platform-go/internal/ent/mqttpublishlog"
)

// MqttPublishLog is the model entity for the MqttPublishLog schema.
type MqttPublishLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id"`
	// Topic holds the value of the "topic" field.
	Topic string `json:"topic"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload"`
	// Qos holds the value of the "qos" field.
	Qos int `json:"qos"`
	// Retained holds the value of the "retained" field.
	Retained bool `json:"retained"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"clientId"`
	// BrokerURL holds the value of the "broker_url" field.
	BrokerURL string `json:"brokerUrl"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime   time.Time `json:"createTime"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MqttPublishLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mqttpublishlog.FieldRetained:
			values[i] = new(sql.NullBool)
		case mqttpublishlog.FieldID, mqttpublishlog.FieldQos:
			values[i] = new(sql.NullInt64)
		case mqttpublishlog.FieldTopic, mqttpublishlog.FieldPayload, mqttpublishlog.FieldClientID, mqttpublishlog.FieldBrokerURL:
			values[i] = new(sql.NullString)
		case mqttpublishlog.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MqttPublishLog fields.
func (_m *MqttPublishLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mqttpublishlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case mqttpublishlog.FieldTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic", values[i])
			} else if value.Valid {
				_m.Topic = value.String
			}
		case mqttpublishlog.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case mqttpublishlog.FieldQos:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field qos", values[i])
			} else if value.Valid {
				_m.Qos = int(value.Int64)
			}
		case mqttpublishlog.FieldRetained:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field retained", values[i])
			} else if value.Valid {
				_m.Retained = value.Bool
			}
		case mqttpublishlog.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case mqttpublishlog.FieldBrokerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field broker_url", values[i])
			} else if value.Valid {
				_m.BrokerURL = value.String
			}
		case mqttpublishlog.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MqttPublishLog.
// This includes values selected through modifiers, order, etc.
func (_m *MqttPublishLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MqttPublishLog.
// Note that you need to call MqttPublishLog.Unwrap() before calling this method if this MqttPublishLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MqttPublishLog) Update() *MqttPublishLogUpdateOne {
	return NewMqttPublishLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MqttPublishLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MqttPublishLog) Unwrap() *MqttPublishLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MqttPublishLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MqttPublishLog) String() string {
	var builder strings.Builder
	builder.WriteString("MqttPublishLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("topic=")
	builder.WriteString(_m.Topic)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("qos=")
	builder.WriteString(fmt.Sprintf("%v", _m.Qos))
	builder.WriteString(", ")
	builder.WriteString("retained=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retained))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("broker_url=")
	builder.WriteString(_m.BrokerURL)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MqttPublishLogs is a parsable slice of MqttPublishLog.
type MqttPublishLogs []*MqttPublishLog
