// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/mqttpublishlog"
)

// MqttPublishLogCreate is the builder for creating a MqttPublishLog entity.
type MqttPublishLogCreate struct {
	config
	mutation *MqttPublishLogMutation
	hooks    []Hook
}

// SetTopic sets the "topic" field.
func (_c *MqttPublishLogCreate) SetTopic(v string) *MqttPublishLogCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *MqttPublishLogCreate) SetPayload(v string) *MqttPublishLogCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillablePayload(v *string) *MqttPublishLogCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetQos sets the "qos" field.
func (_c *MqttPublishLogCreate) SetQos(v int) *MqttPublishLogCreate {
	_c.mutation.SetQos(v)
	return _c
}

// SetNillableQos sets the "qos" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillableQos(v *int) *MqttPublishLogCreate {
	if v != nil {
		_c.SetQos(*v)
	}
	return _c
}

// SetRetained sets the "retained" field.
func (_c *MqttPublishLogCreate) SetRetained(v bool) *MqttPublishLogCreate {
	_c.mutation.SetRetained(v)
	return _c
}

// SetNillableRetained sets the "retained" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillableRetained(v *bool) *MqttPublishLogCreate {
	if v != nil {
		_c.SetRetained(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *MqttPublishLogCreate) SetClientID(v string) *MqttPublishLogCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillableClientID(v *string) *MqttPublishLogCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetBrokerURL sets the "broker_url" field.
func (_c *MqttPublishLogCreate) SetBrokerURL(v string) *MqttPublishLogCreate {
	_c.mutation.SetBrokerURL(v)
	return _c
}

// SetNillableBrokerURL sets the "broker_url" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillableBrokerURL(v *string) *MqttPublishLogCreate {
	if v != nil {
		_c.SetBrokerURL(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *MqttPublishLogCreate) SetCreateTime(v time.Time) *MqttPublishLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *MqttPublishLogCreate) SetNillableCreateTime(v *time.Time) *MqttPublishLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MqttPublishLogCreate) SetID(v uint) *MqttPublishLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MqttPublishLogMutation object of the builder.
func (_c *MqttPublishLogCreate) Mutation() *MqttPublishLogMutation {
	return _c.mutation
}

// Save creates the MqttPublishLog in the database.
func (_c *MqttPublishLogCreate) Save(ctx context.Context) (*MqttPublishLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MqttPublishLogCreate) SaveX(ctx context.Context) *MqttPublishLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MqttPublishLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MqttPublishLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MqttPublishLogCreate) defaults() {
	if _, ok := _c.mutation.Payload(); !ok {
		v := mqttpublishlog.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.Qos(); !ok {
		v := mqttpublishlog.DefaultQos
		_c.mutation.SetQos(v)
	}
	if _, ok := _c.mutation.Retained(); !ok {
		v := mqttpublishlog.DefaultRetained
		_c.mutation.SetRetained(v)
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		v := mqttpublishlog.DefaultClientID
		_c.mutation.SetClientID(v)
	}
	if _, ok := _c.mutation.BrokerURL(); !ok {
		v := mqttpublishlog.DefaultBrokerURL
		_c.mutation.SetBrokerURL(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := mqttpublishlog.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MqttPublishLogCreate) check() error {
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "MqttPublishLog.topic"`)}
	}
	if v, ok := _c.mutation.Topic(); ok {
		if err := mqttpublishlog.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.topic": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "MqttPublishLog.payload"`)}
	}
	if _, ok := _c.mutation.Qos(); !ok {
		return &ValidationError{Name: "qos", err: errors.New(`ent: missing required field "MqttPublishLog.qos"`)}
	}
	if _, ok := _c.mutation.Retained(); !ok {
		return &ValidationError{Name: "retained", err: errors.New(`ent: missing required field "MqttPublishLog.retained"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "MqttPublishLog.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := mqttpublishlog.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BrokerURL(); !ok {
		return &ValidationError{Name: "broker_url", err: errors.New(`ent: missing required field "MqttPublishLog.broker_url"`)}
	}
	if v, ok := _c.mutation.BrokerURL(); ok {
		if err := mqttpublishlog.BrokerURLValidator(v); err != nil {
			return &ValidationError{Name: "broker_url", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.broker_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MqttPublishLog.create_time"`)}
	}
	return nil
}

func (_c *MqttPublishLogCreate) sqlSave(ctx context.Context) (*MqttPublishLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MqttPublishLogCreate) createSpec() (*MqttPublishLog, *sqlgraph.CreateSpec) {
	var (
		_node = &MqttPublishLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mqttpublishlog.Table, sqlgraph.NewFieldSpec(mqttpublishlog.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(mqttpublishlog.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(mqttpublishlog.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Qos(); ok {
		_spec.SetField(mqttpublishlog.FieldQos, field.TypeInt, value)
		_node.Qos = value
	}
	if value, ok := _c.mutation.Retained(); ok {
		_spec.SetField(mqttpublishlog.FieldRetained, field.TypeBool, value)
		_node.Retained = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(mqttpublishlog.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.BrokerURL(); ok {
		_spec.SetField(mqttpublishlog.FieldBrokerURL, field.TypeString, value)
		_node.BrokerURL = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(mqttpublishlog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	return _node, _spec
}

// MqttPublishLogCreateBulk is the builder for creating many MqttPublishLog entities in bulk.
type MqttPublishLogCreateBulk struct {
	config
	err      error
	builders []*MqttPublishLogCreate
}

// Save creates the MqttPublishLog entities in the database.
func (_c *MqttPublishLogCreateBulk) Save(ctx context.Context) ([]*MqttPublishLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MqttPublishLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MqttPublishLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MqttPublishLogCreateBulk) SaveX(ctx context.Context) []*MqttPublishLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MqttPublishLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MqttPublishLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
