// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yu/iot-platform-go/internal/ent/mqttpublishlog"
	"github.com/yu/iot-platform-go/internal/ent/predicate"
)

// MqttPublishLogUpdate is the builder for updating MqttPublishLog entities.
type MqttPublishLogUpdate struct {
	config
	hooks    []Hook
	mutation *MqttPublishLogMutation
}

// Where appends a list predicates to the MqttPublishLogUpdate builder.
func (_u *MqttPublishLogUpdate) Where(ps ...predicate.MqttPublishLog) *MqttPublishLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTopic sets the "topic" field.
func (_u *MqttPublishLogUpdate) SetTopic(v string) *MqttPublishLogUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableTopic(v *string) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MqttPublishLogUpdate) SetPayload(v string) *MqttPublishLogUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillablePayload(v *string) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetQos sets the "qos" field.
func (_u *MqttPublishLogUpdate) SetQos(v int) *MqttPublishLogUpdate {
	_u.mutation.ResetQos()
	_u.mutation.SetQos(v)
	return _u
}

// SetNillableQos sets the "qos" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableQos(v *int) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetQos(*v)
	}
	return _u
}

// AddQos adds value to the "qos" field.
func (_u *MqttPublishLogUpdate) AddQos(v int) *MqttPublishLogUpdate {
	_u.mutation.AddQos(v)
	return _u
}

// SetRetained sets the "retained" field.
func (_u *MqttPublishLogUpdate) SetRetained(v bool) *MqttPublishLogUpdate {
	_u.mutation.SetRetained(v)
	return _u
}

// SetNillableRetained sets the "retained" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableRetained(v *bool) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetRetained(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MqttPublishLogUpdate) SetClientID(v string) *MqttPublishLogUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableClientID(v *string) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetBrokerURL sets the "broker_url" field.
func (_u *MqttPublishLogUpdate) SetBrokerURL(v string) *MqttPublishLogUpdate {
	_u.mutation.SetBrokerURL(v)
	return _u
}

// SetNillableBrokerURL sets the "broker_url" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableBrokerURL(v *string) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetBrokerURL(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MqttPublishLogUpdate) SetCreateTime(v time.Time) *MqttPublishLogUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MqttPublishLogUpdate) SetNillableCreateTime(v *time.Time) *MqttPublishLogUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// Mutation returns the MqttPublishLogMutation object of the builder.
func (_u *MqttPublishLogUpdate) Mutation() *MqttPublishLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MqttPublishLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MqttPublishLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MqttPublishLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MqttPublishLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MqttPublishLogUpdate) check() error {
	if v, ok := _u.mutation.Topic(); ok {
		if err := mqttpublishlog.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := mqttpublishlog.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrokerURL(); ok {
		if err := mqttpublishlog.BrokerURLValidator(v); err != nil {
			return &ValidationError{Name: "broker_url", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.broker_url": %w`, err)}
		}
	}
	return nil
}

func (_u *MqttPublishLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mqttpublishlog.Table, mqttpublishlog.Columns, sqlgraph.NewFieldSpec(mqttpublishlog.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(mqttpublishlog.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(mqttpublishlog.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Qos(); ok {
		_spec.SetField(mqttpublishlog.FieldQos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQos(); ok {
		_spec.AddField(mqttpublishlog.FieldQos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retained(); ok {
		_spec.SetField(mqttpublishlog.FieldRetained, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(mqttpublishlog.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrokerURL(); ok {
		_spec.SetField(mqttpublishlog.FieldBrokerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(mqttpublishlog.FieldCreateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mqttpublishlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MqttPublishLogUpdateOne is the builder for updating a single MqttPublishLog entity.
type MqttPublishLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MqttPublishLogMutation
}

// SetTopic sets the "topic" field.
func (_u *MqttPublishLogUpdateOne) SetTopic(v string) *MqttPublishLogUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableTopic(v *string) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MqttPublishLogUpdateOne) SetPayload(v string) *MqttPublishLogUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillablePayload(v *string) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetQos sets the "qos" field.
func (_u *MqttPublishLogUpdateOne) SetQos(v int) *MqttPublishLogUpdateOne {
	_u.mutation.ResetQos()
	_u.mutation.SetQos(v)
	return _u
}

// SetNillableQos sets the "qos" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableQos(v *int) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetQos(*v)
	}
	return _u
}

// AddQos adds value to the "qos" field.
func (_u *MqttPublishLogUpdateOne) AddQos(v int) *MqttPublishLogUpdateOne {
	_u.mutation.AddQos(v)
	return _u
}

// SetRetained sets the "retained" field.
func (_u *MqttPublishLogUpdateOne) SetRetained(v bool) *MqttPublishLogUpdateOne {
	_u.mutation.SetRetained(v)
	return _u
}

// SetNillableRetained sets the "retained" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableRetained(v *bool) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetRetained(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MqttPublishLogUpdateOne) SetClientID(v string) *MqttPublishLogUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableClientID(v *string) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetBrokerURL sets the "broker_url" field.
func (_u *MqttPublishLogUpdateOne) SetBrokerURL(v string) *MqttPublishLogUpdateOne {
	_u.mutation.SetBrokerURL(v)
	return _u
}

// SetNillableBrokerURL sets the "broker_url" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableBrokerURL(v *string) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetBrokerURL(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MqttPublishLogUpdateOne) SetCreateTime(v time.Time) *MqttPublishLogUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MqttPublishLogUpdateOne) SetNillableCreateTime(v *time.Time) *MqttPublishLogUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// Mutation returns the MqttPublishLogMutation object of the builder.
func (_u *MqttPublishLogUpdateOne) Mutation() *MqttPublishLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the MqttPublishLogUpdate builder.
func (_u *MqttPublishLogUpdateOne) Where(ps ...predicate.MqttPublishLog) *MqttPublishLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MqttPublishLogUpdateOne) Select(field string, fields ...string) *MqttPublishLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MqttPublishLog entity.
func (_u *MqttPublishLogUpdateOne) Save(ctx context.Context) (*MqttPublishLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MqttPublishLogUpdateOne) SaveX(ctx context.Context) *MqttPublishLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MqttPublishLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MqttPublishLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MqttPublishLogUpdateOne) check() error {
	if v, ok := _u.mutation.Topic(); ok {
		if err := mqttpublishlog.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := mqttpublishlog.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrokerURL(); ok {
		if err := mqttpublishlog.BrokerURLValidator(v); err != nil {
			return &ValidationError{Name: "broker_url", err: fmt.Errorf(`ent: validator failed for field "MqttPublishLog.broker_url": %w`, err)}
		}
	}
	return nil
}

func (_u *MqttPublishLogUpdateOne) sqlSave(ctx context.Context) (_node *MqttPublishLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mqttpublishlog.Table, mqttpublishlog.Columns, sqlgraph.NewFieldSpec(mqttpublishlog.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MqttPublishLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mqttpublishlog.FieldID)
		for _, f := range fields {
			if !mqttpublishlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mqttpublishlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(mqttpublishlog.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(mqttpublishlog.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Qos(); ok {
		_spec.SetField(mqttpublishlog.FieldQos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQos(); ok {
		_spec.AddField(mqttpublishlog.FieldQos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retained(); ok {
		_spec.SetField(mqttpublishlog.FieldRetained, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(mqttpublishlog.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrokerURL(); ok {
		_spec.SetField(mqttpublishlog.FieldBrokerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(mqttpublishlog.FieldCreateTime, field.TypeTime, value)
	}
	_node = &MqttPublishLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mqttpublishlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
