// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/yu/iot-platform-go/internal/ent/device"
	"github.com/yu/iot-platform-go/internal/ent/downlinkcmd"
	"github.com/yu/iot-platform-go/internal/ent/mqttpublishlog"
	"github.com/yu/iot-platform-go/internal/ent/schema"
	"github.com/yu/iot-platform-go/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescDeviceID is the schema descriptor for device_id field.
	deviceDescDeviceID := deviceFields[1].Descriptor()
	// device.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	device.DeviceIDValidator = func() func(string) error {
		validators := deviceDescDeviceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(device_id string) error {
			for _, fn := range fns {
				if err := fn(device_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescDeviceName is the schema descriptor for device_name field.
	deviceDescDeviceName := deviceFields[2].Descriptor()
	// device.DefaultDeviceName holds the default value on creation for the device_name field.
	device.DefaultDeviceName = deviceDescDeviceName.Default.(string)
	// device.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	device.DeviceNameValidator = deviceDescDeviceName.Validators[0].(func(string) error)
	// deviceDescDeviceType is the schema descriptor for device_type field.
	deviceDescDeviceType := deviceFields[3].Descriptor()
	// device.DefaultDeviceType holds the default value on creation for the device_type field.
	device.DefaultDeviceType = deviceDescDeviceType.Default.(string)
	// device.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	device.DeviceTypeValidator = deviceDescDeviceType.Validators[0].(func(string) error)
	// deviceDescFirmwareVersion is the schema descriptor for firmware_version field.
	deviceDescFirmwareVersion := deviceFields[4].Descriptor()
	// device.DefaultFirmwareVersion holds the default value on creation for the firmware_version field.
	device.DefaultFirmwareVersion = deviceDescFirmwareVersion.Default.(string)
	// device.FirmwareVersionValidator is a validator for the "firmware_version" field. It is called by the builders before save.
	device.FirmwareVersionValidator = deviceDescFirmwareVersion.Validators[0].(func(string) error)
	// deviceDescIPAddress is the schema descriptor for ip_address field.
	deviceDescIPAddress := deviceFields[5].Descriptor()
	// device.DefaultIPAddress holds the default value on creation for the ip_address field.
	device.DefaultIPAddress = deviceDescIPAddress.Default.(string)
	// device.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	device.IPAddressValidator = deviceDescIPAddress.Validators[0].(func(string) error)
	// deviceDescMACAddress is the schema descriptor for mac_address field.
	deviceDescMACAddress := deviceFields[6].Descriptor()
	// device.DefaultMACAddress holds the default value on creation for the mac_address field.
	device.DefaultMACAddress = deviceDescMACAddress.Default.(string)
	// device.MACAddressValidator is a validator for the "mac_address" field. It is called by the builders before save.
	device.MACAddressValidator = deviceDescMACAddress.Validators[0].(func(string) error)
	// deviceDescLocation is the schema descriptor for location field.
	deviceDescLocation := deviceFields[7].Descriptor()
	// device.DefaultLocation holds the default value on creation for the location field.
	device.DefaultLocation = deviceDescLocation.Default.(string)
	// device.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	device.LocationValidator = deviceDescLocation.Validators[0].(func(string) error)
	// deviceDescOwnerID is the schema descriptor for owner_id field.
	deviceDescOwnerID := deviceFields[8].Descriptor()
	// device.DefaultOwnerID holds the default value on creation for the owner_id field.
	device.DefaultOwnerID = deviceDescOwnerID.Default.(uint)
	// deviceDescStatus is the schema descriptor for status field.
	deviceDescStatus := deviceFields[9].Descriptor()
	// device.DefaultStatus holds the default value on creation for the status field.
	device.DefaultStatus = deviceDescStatus.Default.(string)
	// device.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	device.StatusValidator = deviceDescStatus.Validators[0].(func(string) error)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[11].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[12].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	downlinkcmdFields := schema.DownlinkCmd{}.Fields()
	_ = downlinkcmdFields
	// downlinkcmdDescDeviceID is the schema descriptor for device_id field.
	downlinkcmdDescDeviceID := downlinkcmdFields[1].Descriptor()
	// downlinkcmd.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	downlinkcmd.DeviceIDValidator = func() func(string) error {
		validators := downlinkcmdDescDeviceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(device_id string) error {
			for _, fn := range fns {
				if err := fn(device_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// downlinkcmdDescType is the schema descriptor for type field.
	downlinkcmdDescType := downlinkcmdFields[2].Descriptor()
	// downlinkcmd.DefaultType holds the default value on creation for the type field.
	downlinkcmd.DefaultType = downlinkcmdDescType.Default.(string)
	// downlinkcmd.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	downlinkcmd.TypeValidator = downlinkcmdDescType.Validators[0].(func(string) error)
	// downlinkcmdDescPayload is the schema descriptor for payload field.
	downlinkcmdDescPayload := downlinkcmdFields[3].Descriptor()
	// downlinkcmd.DefaultPayload holds the default value on creation for the payload field.
	downlinkcmd.DefaultPayload = downlinkcmdDescPayload.Default.(string)
	// downlinkcmdDescStatus is the schema descriptor for status field.
	downlinkcmdDescStatus := downlinkcmdFields[4].Descriptor()
	// downlinkcmd.DefaultStatus holds the default value on creation for the status field.
	downlinkcmd.DefaultStatus = downlinkcmdDescStatus.Default.(string)
	// downlinkcmd.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	downlinkcmd.StatusValidator = downlinkcmdDescStatus.Validators[0].(func(string) error)
	// downlinkcmdDescCreatedAt is the schema descriptor for created_at field.
	downlinkcmdDescCreatedAt := downlinkcmdFields[5].Descriptor()
	// downlinkcmd.DefaultCreatedAt holds the default value on creation for the created_at field.
	downlinkcmd.DefaultCreatedAt = downlinkcmdDescCreatedAt.Default.(func() time.Time)
	mqttpublishlogFields := schema.MqttPublishLog{}.Fields()
	_ = mqttpublishlogFields
	// mqttpublishlogDescTopic is the schema descriptor for topic field.
	mqttpublishlogDescTopic := mqttpublishlogFields[1].Descriptor()
	// mqttpublishlog.TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	mqttpublishlog.TopicValidator = func() func(string) error {
		validators := mqttpublishlogDescTopic.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(topic string) error {
			for _, fn := range fns {
				if err := fn(topic); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mqttpublishlogDescPayload is the schema descriptor for payload field.
	mqttpublishlogDescPayload := mqttpublishlogFields[2].Descriptor()
	// mqttpublishlog.DefaultPayload holds the default value on creation for the payload field.
	mqttpublishlog.DefaultPayload = mqttpublishlogDescPayload.Default.(string)
	// mqttpublishlogDescQos is the schema descriptor for qos field.
	mqttpublishlogDescQos := mqttpublishlogFields[3].Descriptor()
	// mqttpublishlog.DefaultQos holds the default value on creation for the qos field.
	mqttpublishlog.DefaultQos = mqttpublishlogDescQos.Default.(int)
	// mqttpublishlogDescRetained is the schema descriptor for retained field.
	mqttpublishlogDescRetained := mqttpublishlogFields[4].Descriptor()
	// mqttpublishlog.DefaultRetained holds the default value on creation for the retained field.
	mqttpublishlog.DefaultRetained = mqttpublishlogDescRetained.Default.(bool)
	// mqttpublishlogDescClientID is the schema descriptor for client_id field.
	mqttpublishlogDescClientID := mqttpublishlogFields[5].Descriptor()
	// mqttpublishlog.DefaultClientID holds the default value on creation for the client_id field.
	mqttpublishlog.DefaultClientID = mqttpublishlogDescClientID.Default.(string)
	// mqttpublishlog.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	mqttpublishlog.ClientIDValidator = mqttpublishlogDescClientID.Validators[0].(func(string) error)
	// mqttpublishlogDescBrokerURL is the schema descriptor for broker_url field.
	mqttpublishlogDescBrokerURL := mqttpublishlogFields[6].Descriptor()
	// mqttpublishlog.DefaultBrokerURL holds the default value on creation for the broker_url field.
	mqttpublishlog.DefaultBrokerURL = mqttpublishlogDescBrokerURL.Default.(string)
	// mqttpublishlog.BrokerURLValidator is a validator for the "broker_url" field. It is called by the builders before save.
	mqttpublishlog.BrokerURLValidator = mqttpublishlogDescBrokerURL.Validators[0].(func(string) error)
	// mqttpublishlogDescCreateTime is the schema descriptor for create_time field.
	mqttpublishlogDescCreateTime := mqttpublishlogFields[7].Descriptor()
	// mqttpublishlog.DefaultCreateTime holds the default value on creation for the create_time field.
	mqttpublishlog.DefaultCreateTime = mqttpublishlogDescCreateTime.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[2].Descriptor()
	// user.DefaultAge holds the default value on creation for the age field.
	user.DefaultAge = userDescAge.Default.(int)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescAccount is the schema descriptor for account field.
	userDescAccount := userFields[4].Descriptor()
	// user.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	user.AccountValidator = func() func(string) error {
		validators := userDescAccount.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(account string) error {
			for _, fn := range fns {
				if err := fn(account); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswd is the schema descriptor for passwd field.
	userDescPasswd := userFields[5].Descriptor()
	// user.PasswdValidator is a validator for the "passwd" field. It is called by the builders before save.
	user.PasswdValidator = func() func(string) error {
		validators := userDescPasswd.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(passwd string) error {
			for _, fn := range fns {
				if err := fn(passwd); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[6].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[7].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userFields[8].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userFields[9].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
