// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// DownlinkCmd is the predicate function for downlinkcmd builders.
type DownlinkCmd func(*sql.Selector)

// MqttPublishLog is the predicate function for mqttpublishlog builders.
type MqttPublishLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
