-- ============================================
-- 用户表 (app_user)
-- 用法: psql -U <user> -d <database> -f app_user.sql
-- ============================================

CREATE TABLE IF NOT EXISTS app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     VARCHAR(100)  NOT NULL,
    passwd      VARCHAR(255)  NOT NULL,
    name        VARCHAR(100)  DEFAULT '',
    email       VARCHAR(255)  DEFAULT '',
    age         BIGINT        DEFAULT 0,
    role        VARCHAR(50)   DEFAULT 'user',
    status      VARCHAR(50)   DEFAULT 'active',
    create_time TIMESTAMPTZ   DEFAULT NOW(),
    update_time TIMESTAMPTZ   DEFAULT NOW(),

    CONSTRAINT chk_user_status CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS app_user_account_key ON app_user (account);
