-- ============================================
-- IoT Platform PostgreSQL 初始化脚本
-- 直接执行即可还原全部表结构（含约束、索引、外键级联）
-- 用法: psql -U <user> -d <database> -f init.sql
-- ============================================

-- ============================================
-- 1. 用户表 (app_user)
-- ============================================
CREATE TABLE IF NOT EXISTS app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     VARCHAR(100)  NOT NULL,
    passwd      VARCHAR(255)  NOT NULL,
    name        VARCHAR(100)  DEFAULT '',
    email       VARCHAR(255)  DEFAULT '',
    age         BIGINT        DEFAULT 0,
    role        VARCHAR(50)   DEFAULT 'user',
    status      VARCHAR(50)   DEFAULT 'active',
    create_time TIMESTAMPTZ   DEFAULT NOW(),
    update_time TIMESTAMPTZ   DEFAULT NOW(),

    CONSTRAINT chk_user_status CHECK (status IN ('active', 'inactive'))
);
CREATE UNIQUE INDEX IF NOT EXISTS app_user_account_key ON app_user (account);

-- ============================================
-- 2. 设备表 (iot_device)
--    主键: id (BIGINT 自增) | 业务主键: device_id (VARCHAR UNIQUE)
--    owner_id → app_user(id) 级联删除
-- ============================================
CREATE TABLE IF NOT EXISTS iot_device (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        VARCHAR(50)   NOT NULL,
    device_name      VARCHAR(100)  NOT NULL DEFAULT '',
    device_type      VARCHAR(50)   NOT NULL DEFAULT '',
    firmware_version VARCHAR(50)   DEFAULT '',
    ip_address       VARCHAR(45)   DEFAULT '',
    mac_address      VARCHAR(17)   DEFAULT '',
    location         VARCHAR(255)  DEFAULT '',
    owner_id         BIGINT        NOT NULL DEFAULT 1,
    status           VARCHAR(50)   DEFAULT 'OFFLINE',
    last_active_time TIMESTAMPTZ,
    created_at       TIMESTAMPTZ   DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   DEFAULT NOW(),
    category_id      VARCHAR(100)  DEFAULT '',

    CONSTRAINT chk_device_status CHECK (status IN ('ONLINE', 'OFFLINE')),
    CONSTRAINT fk_device_owner FOREIGN KEY (owner_id) REFERENCES app_user(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS device_device_id        ON iot_device (device_id);
CREATE INDEX        IF NOT EXISTS idx_iot_device_owner_id ON iot_device (owner_id);

-- ============================================
-- 3. 下行命令表 (iot_downlink_cmd)
--    device_id → iot_device(device_id) 级联删除
-- ============================================
CREATE TABLE IF NOT EXISTS iot_downlink_cmd (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(50)  NOT NULL,
    type       VARCHAR(50)  NOT NULL DEFAULT '',
    payload    TEXT         NOT NULL DEFAULT '',
    status     VARCHAR(20)  DEFAULT 'pending',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cmd_device FOREIGN KEY (device_id) REFERENCES iot_device(device_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS downlinkcmd_device_id ON iot_downlink_cmd (device_id);

-- ============================================
-- 4. MQTT 发布日志表 (mqtt_publish_log)
--    写多读少，create_time 使用 BRIN 索引
-- ============================================
CREATE TABLE IF NOT EXISTS mqtt_publish_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic       VARCHAR(255) NOT NULL,
    payload     TEXT         NOT NULL DEFAULT '',
    qos         INTEGER      DEFAULT 0,
    retained    BOOLEAN      DEFAULT FALSE,
    client_id   VARCHAR(128) NOT NULL DEFAULT '',
    broker_url  VARCHAR(255) NOT NULL DEFAULT '',
    create_time TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS mqttpublishlog_create_time
    ON mqtt_publish_log USING brin (create_time) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_topic ON mqtt_publish_log (topic);
