-- ============================================
-- IoT Platform PostgreSQL 初始化脚本
-- 直接执行即可还原全部表结构（含约束、索引、外键级联）
--
-- ⚠️ 仅用于【全新环境】初始化。存量库升级须知：
--   1. iot_device 主键已从遗留的 id (bigint identity) 改为 device_id（2026-09 清理），
--      存量库需手工执行：删除原始 id 列与旧唯一索引 device_device_id，重建主键；
--   2. app_user.status 默认值改为 'ACTIVE'（与 ent 校验一致）；
--   3. 表结构合并（2026-09）：
--      - iot_device_sensor + iot_device_actuator → iot_device_thing（kind 判别，窄表）
--      - iot_downlink_cmd + mqtt_publish_log      → iot_message_log（direction 判别）
--      存量库需按业务数据迁移后删除旧表。
--   CREATE TABLE IF NOT EXISTS 不会改动已存在的表，请勿对存量库直接重跑本脚本。
-- 用法: psql -U <user> -d <database> -f init.sql
-- ============================================

-- ============================================
-- 1. 用户表 (app_user)
-- ============================================
CREATE TABLE IF NOT EXISTS app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     VARCHAR(100)  NOT NULL,
    passwd      VARCHAR(255)  NOT NULL,
    name        VARCHAR(100)  DEFAULT '',
    email       VARCHAR(255)  DEFAULT '',
    age         BIGINT        DEFAULT 0,
    role        VARCHAR(50)   DEFAULT 'user',
    status      VARCHAR(50)   DEFAULT 'ACTIVE',
    create_time TIMESTAMPTZ   DEFAULT NOW(),
    update_time TIMESTAMPTZ   DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS user_account ON app_user (account);

-- ============================================
-- 2. 设备表 (iot_device)
--    主键: device_id (VARCHAR, 应用生成6位hex)
--    owner_id → app_user(id) 级联删除
-- ============================================
CREATE TABLE IF NOT EXISTS iot_device (
    device_id        VARCHAR(50)   PRIMARY KEY,
    device_name      VARCHAR(100)  NOT NULL DEFAULT '',
    device_type      VARCHAR(50)   NOT NULL DEFAULT '',
    firmware_version VARCHAR(50)   DEFAULT '',
    ip_address       VARCHAR(45)   DEFAULT '',
    mac_address      VARCHAR(17)   DEFAULT '',
    location         VARCHAR(255)  DEFAULT '',
    owner_id         BIGINT        NOT NULL DEFAULT 1,
    status           VARCHAR(50)   DEFAULT 'OFFLINE',
    last_active_time TIMESTAMPTZ,
    created_at       TIMESTAMPTZ   DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   DEFAULT NOW(),

    CONSTRAINT chk_device_status CHECK (status IN ('ONLINE', 'OFFLINE', 'ACTIVE')),
    CONSTRAINT iot_device_app_user_devices FOREIGN KEY (owner_id) REFERENCES app_user(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS device_owner_id ON iot_device (owner_id);

-- ============================================
-- 3. 设备配置快照表 (iot_device_config)
--    device_id 唯一，→ iot_device(device_id) 级联删除
-- ============================================
CREATE TABLE IF NOT EXISTS iot_device_config (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        VARCHAR(50),
    version          BIGINT       NOT NULL DEFAULT 1,
    payload          TEXT         NOT NULL DEFAULT '',
    status           VARCHAR(20)  DEFAULT 'pending',
    reported_version BIGINT       NOT NULL DEFAULT 0,
    reported_payload TEXT         NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT iot_device_config_iot_device_config FOREIGN KEY (device_id) REFERENCES iot_device(device_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS deviceconfig_device_id ON iot_device_config (device_id);

-- ============================================
-- 4. 设备物模型表 (iot_device_thing) — 传感器/执行器统一存储
--    kind: sensor | actuator，(device_id, kind, thing_id) 唯一
--    specs: JSON 文本（含 kind 专有字段：sensor 的 type/dataType/unit/reportInterval；
--           actuator 的 driver；以及物模型定义体）
--    → iot_device(device_id) 级联删除
-- ============================================
CREATE TABLE IF NOT EXISTS iot_device_thing (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(50),
    kind       VARCHAR(16)  NOT NULL,
    thing_id   VARCHAR(50)  NOT NULL,
    name       VARCHAR(100) NOT NULL DEFAULT '',
    specs      TEXT         NOT NULL DEFAULT '',
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT iot_device_thing_iot_device_things FOREIGN KEY (device_id) REFERENCES iot_device(device_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS devicething_device_id_kind_thing_id
    ON iot_device_thing (device_id, kind, thing_id);

-- ============================================
-- 5. 设备消息日志表 (iot_message_log) — 下行命令 + 上行 MQTT 发布统一存储
--    direction: down（命令，status=pending/sent/delivered）| up（设备发布，category=telemetry/config_report/other）
--    → iot_device(device_id) 级联删除；create_time 使用 BRIN 索引
-- ============================================
CREATE TABLE IF NOT EXISTS iot_message_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction   VARCHAR(8)   NOT NULL,
    category    VARCHAR(20)  NOT NULL DEFAULT '',
    type        VARCHAR(50)  NOT NULL DEFAULT '',
    topic       VARCHAR(255) NOT NULL DEFAULT '',
    payload     TEXT         NOT NULL DEFAULT '',
    qos         BIGINT       NULL DEFAULT 0,
    retained    BOOLEAN      NULL DEFAULT FALSE,
    client_id   VARCHAR(128) NOT NULL DEFAULT '',
    broker_url  VARCHAR(255) NOT NULL DEFAULT '',
    status      VARCHAR(20)  NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    device_id   VARCHAR(50),

    CONSTRAINT iot_message_log_iot_device_messages FOREIGN KEY (device_id) REFERENCES iot_device(device_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS messagelog_device_id ON iot_message_log (device_id);
CREATE INDEX IF NOT EXISTS messagelog_direction_created_at ON iot_message_log (direction, created_at);
CREATE INDEX IF NOT EXISTS messagelog_topic ON iot_message_log (topic);
CREATE INDEX IF NOT EXISTS messagelog_created_at
    ON iot_message_log USING brin (created_at) WITH (pages_per_range = 32);
