-- ============================================
-- 设备表 (iot_device)
-- 主键: id (BIGINT, ent 自增) | 业务主键: device_id (VARCHAR UNIQUE, 应用生成6位hex)
-- 用法: psql -U <user> -d <database> -f iot_device.sql
-- ============================================

CREATE TABLE IF NOT EXISTS iot_device (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        VARCHAR(50)   NOT NULL,
    device_name      VARCHAR(100)  NOT NULL DEFAULT '',
    device_type      VARCHAR(50)   NOT NULL DEFAULT '',
    firmware_version VARCHAR(50)   DEFAULT '',
    ip_address       VARCHAR(45)   DEFAULT '',
    mac_address      VARCHAR(17)   DEFAULT '',
    location         VARCHAR(255)  DEFAULT '',
    owner_id         BIGINT        NOT NULL DEFAULT 1,
    status           VARCHAR(50)   DEFAULT 'OFFLINE',
    last_active_time TIMESTAMPTZ,
    created_at       TIMESTAMPTZ   DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   DEFAULT NOW(),
    category_id      VARCHAR(100)  DEFAULT '',

    CONSTRAINT chk_device_status CHECK (status IN ('ONLINE', 'OFFLINE')),
    CONSTRAINT fk_device_owner FOREIGN KEY (owner_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS device_device_id        ON iot_device (device_id);
CREATE INDEX        IF NOT EXISTS idx_iot_device_owner_id ON iot_device (owner_id);
