-- ============================================
-- MQTT 发布日志表 (mqtt_publish_log)
-- 写多读少，create_time 使用 BRIN 索引（比 B-tree 小 ~1000 倍）
-- 用法: psql -U <user> -d <database> -f mqtt_publish_log.sql
-- ============================================

CREATE TABLE IF NOT EXISTS mqtt_publish_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic       VARCHAR(255) NOT NULL,
    payload     TEXT         NOT NULL DEFAULT '',
    qos         INTEGER      DEFAULT 0,
    retained    BOOLEAN      DEFAULT FALSE,
    client_id   VARCHAR(128) NOT NULL DEFAULT '',
    broker_url  VARCHAR(255) NOT NULL DEFAULT '',
    create_time TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- BRIN 索引：专为海量顺序写入的时间序列数据设计，写入开销极低
CREATE INDEX IF NOT EXISTS mqttpublishlog_create_time
    ON mqtt_publish_log USING brin (create_time) WITH (pages_per_range = 32);

CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_topic ON mqtt_publish_log (topic);
