-- ============================================
-- MQTT 发布日志表 (mqtt_publish_log)
-- 用法: psql -U <user> -d <database> -f mqtt_publish_log.sql
-- ============================================

CREATE TABLE IF NOT EXISTS mqtt_publish_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic       VARCHAR(255) NOT NULL,
    payload     TEXT         DEFAULT '',
    qos         INTEGER      DEFAULT 0,
    retained    BOOLEAN      DEFAULT FALSE,
    client_id   VARCHAR(128) DEFAULT '',
    broker_url  VARCHAR(255) DEFAULT '',
    create_time TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_topic       ON mqtt_publish_log (topic);
CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_create_time ON mqtt_publish_log (create_time DESC);
