-- ============================================
-- IoT Platform PostgreSQL 初始化脚本
-- 直接执行即可还原全部表结构
-- 用法: psql -U <user> -d <database> -f init.sql
-- ============================================

-- ============================================
-- 1. 用户表
-- ============================================
CREATE TABLE IF NOT EXISTS app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     VARCHAR(100)  NOT NULL,
    passwd      VARCHAR(255)  NOT NULL,
    name        VARCHAR(100)  DEFAULT '',
    email       VARCHAR(255)  DEFAULT '',
    age         INTEGER       DEFAULT 0,
    role        VARCHAR(50)   DEFAULT 'user',
    status      VARCHAR(50)   DEFAULT 'active',
    create_time TIMESTAMPTZ   DEFAULT NOW(),
    update_time TIMESTAMPTZ   DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_app_user_account ON app_user (account);

-- ============================================
-- 2. 设备表（主键: device_id，由应用生成6位hex，无自增）
-- ============================================
CREATE TABLE IF NOT EXISTS iot_device (
    device_id         VARCHAR(50)  PRIMARY KEY,
    device_name       VARCHAR(100) DEFAULT '',
    device_type       VARCHAR(50)  DEFAULT '',
    firmware_version  VARCHAR(50)  DEFAULT '',
    ip_address        VARCHAR(45)  DEFAULT '',
    mac_address       VARCHAR(17)  DEFAULT '',
    location          VARCHAR(255) DEFAULT '',
    owner_id          BIGINT       DEFAULT 1,
    status            VARCHAR(50)  DEFAULT 'OFFLINE',
    last_active_time  TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_iot_device_owner_id ON iot_device (owner_id);

-- ============================================
-- 3. 下放命令表
-- ============================================
CREATE TABLE IF NOT EXISTS iot_downlink_cmd (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(50)  NOT NULL,
    type       VARCHAR(50)  DEFAULT '',
    payload    TEXT         DEFAULT '',
    status     VARCHAR(20)  DEFAULT 'pending',
    created_at TIMESTAMPTZ  DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_iot_downlink_cmd_device_id ON iot_downlink_cmd (device_id);

-- ============================================
-- 4. MQTT 发布日志表
-- ============================================
CREATE TABLE IF NOT EXISTS mqtt_publish_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic       VARCHAR(255) NOT NULL,
    payload     TEXT         DEFAULT '',
    qos         INTEGER      DEFAULT 0,
    retained    BOOLEAN      DEFAULT FALSE,
    client_id   VARCHAR(128) DEFAULT '',
    broker_url  VARCHAR(255) DEFAULT '',
    create_time TIMESTAMPTZ  DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_topic ON mqtt_publish_log (topic);
CREATE INDEX IF NOT EXISTS idx_mqtt_publish_log_create_time ON mqtt_publish_log (create_time DESC);
